language: python
dist: bionic
python:
  - '3.8'
services:
  - redis
before_install:
  - sudo apt-get install -y libimage-exiftool-perl dcraw wget
  # We use Debian Buster for our Docker image but the closest distro we can get in Travis is Ubuntu Bionic. This upgrades the version of GLIBC so that our custom Tensorflow build works.
  - wget http://gb.archive.ubuntu.com/ubuntu/pool/main/g/glibc/locales_2.31-0ubuntu9_all.deb
  - wget http://gb.archive.ubuntu.com/ubuntu/pool/main/g/glibc/libc6_2.31-0ubuntu9_amd64.deb
  - wget http://gb.archive.ubuntu.com/ubuntu/pool/main/g/glibc/libc-bin_2.31-0ubuntu9_amd64.deb
  - sudo apt --fix-broken install locales_2.31-0ubuntu9_all.deb libc6_2.31-0ubuntu9_amd64.deb libc-bin_2.31-0ubuntu9_amd64.deb
install:
  - pip install -r requirements.txt
script:
  - coverage run test.py
after_success:
  - pip install codecov
  - codecov
